

using System;

class Program {
    static void Main(string[] args) {
        Console.BackgroundColor = ConsoleColor.Yellow;
        Console.Clear();
        Console.ForegroundColor = ConsoleColor.Black;
        Console.SetCursorPosition(2, 2);
        Console.WriteLine("╔═══════════════════════════════════════════════════════╗");
        Console.SetCursorPosition(2, 3);
        Console.WriteLine("║                                                       ║");
        Console.SetCursorPosition(2, 4);
        Console.WriteLine("║                                                       ║");
        Console.SetCursorPosition(2, 5);
        Console.WriteLine("║                                                       ║");
        Console.SetCursorPosition(2, 6);
        Console.WriteLine("║                                                       ║");
        Console.SetCursorPosition(2, 7);
        Console.WriteLine("║                                                       ║");
        Console.SetCursorPosition(2, 8);
        Console.WriteLine("║                                                       ║");
        Console.SetCursorPosition(2, 9);
        Console.WriteLine("║                                                       ║");
        Console.SetCursorPosition(2, 10);
        Console.WriteLine("║                                                       ║");
        Console.SetCursorPosition(2, 11);
        Console.WriteLine("╚═══════════════════════════════════════════════════════╝");
        Console.ForegroundColor = ConsoleColor.Black;
        Console.SetCursorPosition(24, 3);
        Console.WriteLine("Exercicio 3!");
        Console.ForegroundColor = ConsoleColor.Black;
        int opcao;
        double sal, nsal, dif;
        Console.SetCursorPosition(4, 5);
        Console.Write("1 – Gerente. \n");
        Console.SetCursorPosition(4, 6);
        Console.Write("2 – Analista. \n");
        Console.SetCursorPosition(4, 7);
        Console.Write("3 – Técnico. \n");
        Console.SetCursorPosition(4, 9);
        Console.Write("Informe seu sálario: ");
        sal = Convert.ToDouble(Console.ReadLine());
        Console.SetCursorPosition(4, 10);
        Console.Write("Escolha uma operação:");
        Console.SetCursorPosition(26, 10);
        Console.SetCursorPosition(28, 10);        
        Console.WriteLine("( )");
        Console.SetCursorPosition(29, 10);
        opcao = Convert.ToInt32(Console.ReadLine());
        switch(opcao) {
            case 1:
                Console.BackgroundColor = ConsoleColor.Yellow;
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Black;
                Console.SetCursorPosition(2, 2);
                Console.WriteLine("╔═══════════════════════════════════════════════════════╗");
                Console.SetCursorPosition(2, 3);
                Console.WriteLine("║                                                       ║");
                Console.SetCursorPosition(2, 4);
                Console.WriteLine("║                                                       ║");
                Console.SetCursorPosition(2, 5);
                Console.WriteLine("║                                                       ║");
                Console.SetCursorPosition(2, 6);
                Console.WriteLine("║                                                       ║");
                Console.SetCursorPosition(2, 7);
                Console.WriteLine("║                                                       ║");
                Console.SetCursorPosition(2, 8);
                Console.WriteLine("║                                                       ║");
                Console.SetCursorPosition(2, 9);
                Console.WriteLine("║                                                       ║");
                Console.SetCursorPosition(2, 10);
                Console.WriteLine("║                                                       ║");
                Console.SetCursorPosition(2, 11);
                Console.WriteLine("╚═══════════════════════════════════════════════════════╝");
                Console.ForegroundColor = ConsoleColor.Black;
                Console.SetCursorPosition(24, 3);
                Console.WriteLine("Analista");
                Console.ForegroundColor = ConsoleColor.Black;
                nsal = sal+(sal*0.10);
                dif = nsal-sal;
                Console.SetCursorPosition(4, 7);
                Console.Write("sálario antigo: R$"+sal);
                Console.SetCursorPosition(4, 8);
                Console.Write("novo sálario: R$"+nsal);
                Console.SetCursorPosition(4, 9);
                Console.Write("diferença: R$"+dif);
            break;

            case 2:
                Console.BackgroundColor = ConsoleColor.Yellow;
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Black;
                Console.SetCursorPosition(2, 2);
                Console.WriteLine("╔═══════════════════════════════════════════════════════╗");
                Console.SetCursorPosition(2, 3);
                Console.WriteLine("║                                                       ║");
                Console.SetCursorPosition(2, 4);
                Console.WriteLine("║                                                       ║");
                Console.SetCursorPosition(2, 5);
                Console.WriteLine("║                                                       ║");
                Console.SetCursorPosition(2, 6);
                Console.WriteLine("║                                                       ║");
                Console.SetCursorPosition(2, 7);
                Console.WriteLine("║                                                       ║");
                Console.SetCursorPosition(2, 8);
                Console.WriteLine("║                                                       ║");
                Console.SetCursorPosition(2, 9);
                Console.WriteLine("║                                                       ║");
                Console.SetCursorPosition(2, 10);
                Console.WriteLine("║                                                       ║");
                Console.SetCursorPosition(2, 11);
                Console.WriteLine("╚═══════════════════════════════════════════════════════╝");
                Console.ForegroundColor = ConsoleColor.Black;
                Console.SetCursorPosition(24, 3);
                Console.WriteLine("Gerente");
                Console.ForegroundColor = ConsoleColor.Black;
                nsal = sal+(sal*0.20);
                dif = nsal-sal;
                Console.SetCursorPosition(4, 7);
                Console.Write("sálario antigo: R$"+sal);
                Console.SetCursorPosition(4, 8);
                Console.Write("novo sálario: R$"+nsal);
                Console.SetCursorPosition(4, 9);
                Console.Write("diferença: R$"+dif);
            break;

            case 3:
                Console.BackgroundColor = ConsoleColor.Yellow;
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Black;
                Console.SetCursorPosition(2, 2);
                Console.WriteLine("╔═══════════════════════════════════════════════════════╗");
                Console.SetCursorPosition(2, 3);
                Console.WriteLine("║                                                       ║");
                Console.SetCursorPosition(2, 4);
                Console.WriteLine("║                                                       ║");
                Console.SetCursorPosition(2, 5);
                Console.WriteLine("║                                                       ║");
                Console.SetCursorPosition(2, 6);
                Console.WriteLine("║                                                       ║");
                Console.SetCursorPosition(2, 7);
                Console.WriteLine("║                                                       ║");
                Console.SetCursorPosition(2, 8);
                Console.WriteLine("║                                                       ║");
                Console.SetCursorPosition(2, 9);
                Console.WriteLine("║                                                       ║");
                Console.SetCursorPosition(2, 10);
                Console.WriteLine("║                                                       ║");
                Console.SetCursorPosition(2, 11);
                Console.WriteLine("╚═══════════════════════════════════════════════════════╝");
                Console.ForegroundColor = ConsoleColor.Black;
                Console.SetCursorPosition(24, 3);
                Console.WriteLine("Técnico");
                Console.ForegroundColor = ConsoleColor.Black;
                nsal = sal+(sal*0.30);
                dif = nsal-sal;
                Console.SetCursorPosition(4, 7);
                Console.Write("sálario antigo: R$"+sal);
                Console.SetCursorPosition(4, 8);
                Console.Write("novo sálario: R$"+nsal);
                Console.SetCursorPosition(4, 9);
                Console.Write("diferença: R$"+dif);
            break;

            default:
                Console.BackgroundColor = ConsoleColor.Yellow;
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Black;
                Console.SetCursorPosition(2, 2);
                Console.WriteLine("╔═══════════════════════════════════════════════════════╗");
                Console.SetCursorPosition(2, 3);
                Console.WriteLine("║                                                       ║");
                Console.SetCursorPosition(2, 4);
                Console.WriteLine("║                                                       ║");
                Console.SetCursorPosition(2, 5);
                Console.WriteLine("║                                                       ║");
                Console.SetCursorPosition(2, 6);
                Console.WriteLine("║                                                       ║");
                Console.SetCursorPosition(2, 7);
                Console.WriteLine("║                                                       ║");
                Console.SetCursorPosition(2, 8);
                Console.WriteLine("║                                                       ║");
                Console.SetCursorPosition(2, 9);
                Console.WriteLine("║                                                       ║");
                Console.SetCursorPosition(2, 10);
                Console.WriteLine("║                                                       ║");
                Console.SetCursorPosition(2, 11);
                Console.WriteLine("╚═══════════════════════════════════════════════════════╝");
                Console.ForegroundColor = ConsoleColor.Black;
                Console.SetCursorPosition(24, 3);
                Console.WriteLine("Outros");
                Console.ForegroundColor = ConsoleColor.Black;
                nsal = sal+(sal*0.40);
                dif = nsal-sal;
                Console.SetCursorPosition(4, 7);
                Console.Write("sálario antigo: R$"+sal);
                Console.SetCursorPosition(4, 8);
                Console.Write("novo sálario: R$"+nsal);
                Console.SetCursorPosition(4, 9);
                Console.Write("diferença: R$"+dif);
            break;    
        }    
    }
}